### ISSUE TITLE
Tracking API : POD not inluded in the track response

### ISSUE THREAD

**Issue by suma11teeka** [UPS-API/api-documentation#68] opened 2024-03-26 22:27 UTC
The new REST API doesn't return POD (proof of delivery) or a signature photo, even though the request has 'returnSignature' set to true. Any resolution to this issue would be greatly appreciated. Below is the endpoint I am using to retrieve tracking responses
https://onlinetools.ups.com/api/track/v1/details/{trackingnumber}?locale=en_US&returnSignature=true&returnMilestones=true.

Based on the API documentation provided at https://developer.ups.com/api/reference?loc=en_US#operation/getSingleTrackResponseUsingGET, the endpoint returns the Proof of Delivery (POD). However, when testing it, the actual response doesn't include the POD for the same tracking number.

![image](https://github.com/UPS-API/api-documentation/assets/89099849/e67f81d2-8f96-4e82-9c48-50c04a7d6d17)

**Comment by david-szabo97** [comment] 2024-04-02 12:53
Same issue here. There is a "returnPOD" parameter in the API documentation, but not in the API spec. There is also a "pod" property on the "deliveryInformation" in the API documentation, which gets filled when "returnPOD" is "true". Both are missing from the OpenAPI spec.

We keep an edited version of the OpenAPI spec that includes these two missing properties.

**Comment by ipavkovic** [comment] 2024-04-03 07:25
@david-szabo97  nice to know. In general: this is a duplicate of #57 , or?

**Comment by david-szabo97** [comment] 2024-04-03 12:30
> @david-szabo97 nice to know. In general: this is a duplicate of #57 , or?

No, these are two different parameters with two different outcomes.

**Comment by ipavkovic** [comment] 2024-04-03 12:46
@david-szabo97 true. Are you happy with the values found in DeliveryInformation.pod.content? I raised #76 after some analysis.

**Comment by suma11teeka** [comment] 2024-04-03 13:47
> Same issue here. There is a "returnPOD" parameter in the API documentation, but not in the API spec. There is also a "pod" property on the "deliveryInformation" in the API documentation, which gets filled when "returnPOD" is "true". Both are missing from the OpenAPI spec.
> 
> We keep an edited version of the OpenAPI spec that includes these two missing properties.

Thanks, having returnPOD=true parameter worked for me

**Comment by suma11teeka** [comment] 2024-04-03 16:22
resolved

**Closed** 2024-04-03 16:22 UTC

**Comment by UPSRahul** [comment] 2024-04-04 14:09
> Same issue here. There is a "returnPOD" parameter in the API documentation, but not in the API spec. There is also a "pod" property on the "deliveryInformation" in the API documentation, which gets filled when "returnPOD" is "true". Both are missing from the OpenAPI spec.
> 
> We keep an edited version of the OpenAPI spec that includes these two missing properties.

Hi, thank you for the collaboration in this thread. Our documentation push yesterday added these two missing fields.
