### ISSUE TITLE
App registration is not working

### ISSUE THREAD

**Issue by tplsoft** [UPS-API/api-documentation#32] opened 2023-11-28 13:52 UTC
callback url is not saved it looks like both App Name and callback url inputs mapped to same model as both their IDs are "appName" can you please fix this as I keep getting 'Bad Request' with errordescription: Invalid Redirect URL

**Comment by elidrissidev** [comment] 2023-11-30 13:15
I first faced this issue like two months ago, I thought it would've been fixed by now...

**Comment by UPSRahulBhatnagar** [comment] 2023-11-30 21:06
Hi, thank you for your comment. Would you mind providing a bit more detail regarding your inquiry?

**Comment by elidrissidev** [comment] 2023-12-09 09:53
@UPSRahulBhatnagar The issue is when you try to set or update the Callback URL of an App and save nothing happens. The ajax request fails with this error:
`You don't have permission to access "http://developer.ups.com/dpui/api/UpdateApplication" on this server.`

**Comment by UPSRahulBhatnagar** [comment] 2023-12-20 16:29
Hi, thank you for the follow-up. This issue is being investigated and we will update the thread once we have a resolution.

**Comment by UPSRahul** [comment] 2024-04-03 13:11
Hi, we have resolved the issue. For similar inquiries, please feel free to contact the UPS Help Desk (https://developer.ups.com/contactus) for real-time debugging.

**Closed by UPSRahul** 2024-04-03 13:11 UTC
